### PR TITLE
chore(typescript): convert tests to use typescript as well

### PR DESCRIPTION
**Pull request by PeterMK85**
### Description

_Describe the changes and motivations for the pull request, unless obvious from the title._

### Review

- [x] Verify that all classes affected by the changes have **good** top-level documentation.
- [ ] Verify that new code has been covered with specs (and features if applicable).
- [ ] Verify that a corresponding meaningful changelog entry has been added (`* Add Github pull request template`), for this change if applicable.
- [ ] Test manually.
- [ ] Get two :+1: from code review.

### Pre-merge checklist

- [ ] The PR relates to a single subject with a clear title and description in grammatically correct, complete sentences.
- [ ] Verify that all new dependencies are included in `package.json`.
- [ ] Double check the quality of [commit messages](http://chris.beams.io/posts/git-commit/).
- [ ] Squash related commits together.
- [ ] Verify the branch name starts with `NNNN` where `NNNN` is the issue number.

### Screenshots

| Before                                        | After                                         |
| --------------------------------------------- | --------------------------------------------- |
| _Insert screenshots and/or screen recordings_ | _Insert screenshots and/or screen recordings_ |

### Other

_Provide additional notes, remarks, links, mention specific people to review,…_

### CODE REVIEW

**Comment by havenchyk** [comment]
I don’t see benefit in this change, let simply rewrite tests with TS

**Comment by PeterMK85** [comment]
@havenchyk 
You mean to have tests in TS? I think on a longer run, it beneficial because this is actually a proper way to test. (Props has been passed with a proper type... etc)

**Comment by havenchyk** [comment]
@PeterMK85 I mean https://github.com/toptal/simple-react-calendar/issues/104 currently tests are not really reliable, I started rewriting them, but it's in early state

**Comment by PeterMK85** [comment]
I would merge this and the prettier PR in, and we would have a base with the desired TS base, with the desired code formatting.

And than we can start to create FCs with test coverage.

IMHO of course 
@havenchyk

**Comment by havenchyk** [comment]
You’re a maintainer so it’s up to you. I don’t see benefits on migrating specs or applying code style to something that is going to be removed

**Comment by PeterMK85** [comment]
We have multiple this (like class components, spread logic, but because we don't want to do it in a single PR, we need to start somehow)

**Pull request merged**
